blueprint:
  name: Create Todo Helper Entity
  description: Create an input_text helper with a given name for use with the custom-todo-card
  domain: script
  input:
    name:
      name: Entity Name Suffix
      description: e.g., 'baby_tasks' will create input_text.custom_todo_baby_tasks
      selector:
        text:
mode: queued
sequence:
  - service: input_text.set_value
    data:
      entity_id: "input_text.custom_todo_{{ name }}"
      value: '{"tasks":[]}'
